"""
Static pool of neutral thinking-bridge phrases.

Rule: every phrase here must be content-neutral — it signals "I heard you and
I am processing" without asserting agreement, approval, or any claim about what
the learner said. That way it cannot clash with whatever the LLM says next.

Unsafe (removed): "Makes perfect sense.", "Good point.", "Spot on.", "That's valid.",
"Agreed.", "Well said.", "Smart thinking." — these assert a position and sound
absurd when the LLM then challenges or redirects.
"""

THINKING_PHRASES: list[str] = [
    # ── Pure sounds ─────────────────────────────────────────────────────────
    "Hmm.",
    "Hmm...",
    "Hm.",
    "Hm...",
    "Mm.",
    "Mm...",
    "Mmm.",
    "Mmm...",
    "Mm-hmm.",
    "Mm-hmm...",
    "Mhm.",
    "Mhm...",
    "Uh-huh.",
    "Uh-huh...",
    "Oh.",
    "Oh...",
    "Ah.",
    "Ah...",
    "Ooh.",
    "Ooh...",

    # ── One-word neutral reactions ───────────────────────────────────────────
    "Right.",
    "Right...",
    "Yeah.",
    "Yeah...",
    "Yep.",
    "Yep...",
    "Okay.",
    "Okay...",
    "Sure.",
    "Sure...",
    "Interesting.",
    "Interesting...",
    "Indeed.",
    "Indeed...",
    "Noted.",
    "Noted...",
    "Understood.",
    "Understood...",
    "Heard.",
    "Clear.",
    "Clear...",
    "Received.",

    # ── Thinking out loud ────────────────────────────────────────────────────
    "Let me think.",
    "Let me think...",
    "Let me think about that.",
    "Let me think about that...",
    "Let me consider that.",
    "Let me consider that...",
    "Let me see.",
    "Let me see...",
    "Let me work through that.",
    "Let me work through that...",
    "Let me reason through that.",
    "Let me reason through that...",
    "Let me process that.",
    "Let me process that...",
    "Let me run through that.",
    "Let me run through that...",
    "Let me sit with that.",
    "Let me sit with that...",
    "Let me just think.",
    "Let me just think...",
    "Let me think this through.",
    "Let me think this through...",
    "Thinking through that.",
    "Thinking through that...",
    "Processing that.",
    "Processing that...",
    "Working through it.",
    "Working through it...",
    "Running through that.",
    "Running through that...",
    "Reasoning through that.",
    "Reasoning through that...",
    "Considering that.",
    "Considering that...",

    # ── Neutral receipt acknowledgments ──────────────────────────────────────
    "I see.",
    "I see...",
    "I see that.",
    "I see that...",
    "Ah, I see.",
    "Ah, I see...",
    "Oh, I see.",
    "Oh, I see...",
    "Right, I see.",
    "Right, I see...",
    "Yeah, I see.",
    "Yeah, I see...",
    "Okay, I see.",
    "Okay, I see...",
    "Hmm, I see.",
    "Hmm, I see...",
    "I follow.",
    "I follow...",
    "I follow you.",
    "I follow you...",
    "I follow that.",
    "I follow that...",
    "I follow so far.",
    "I follow so far...",
    "Still following.",
    "Still following...",
    "With you so far.",
    "With you so far...",
    "Right, with you.",
    "Right, with you...",
    "Yeah, with you.",
    "Yeah, with you...",
    "I'm following.",
    "I'm following...",
    "I'm with you.",
    "I'm with you...",
    "Following along.",
    "Following along...",
    "Following you.",
    "Following you...",
    "Got it.",
    "Got it...",
    "Right, got it.",
    "Right, got it...",
    "Yeah, got it.",
    "Yeah, got it...",
    "Okay, got it.",
    "Okay, got it...",
    "Hmm, got it.",
    "Hmm, got it...",

    # ── Thinking bridges with connectives ────────────────────────────────────
    "Right, so...",
    "Okay, so...",
    "Yeah, so...",
    "Hmm, so...",
    "Well, so...",
    "And so...",
    "So then...",
    "Right, and...",
    "Okay, and...",
    "Yeah, and...",
    "Right, well...",
    "Okay, well...",
    "Yeah, well...",
    "Hmm, well...",
    "Right, but...",
    "Hmm, but...",
    "Yeah, but...",
    "Right then...",
    "Okay then...",
    "Hmm, then...",
    "Yeah, then...",
    "So then...",
    "Well then...",
    "And then...",
    "So, yeah...",
    "Right, yeah...",
    "Okay, yeah...",
    "Hmm, yeah...",
    "Okay, right...",
    "Sure, right...",
    "Yeah, right...",
    "Hmm, right...",
    "Ah, right...",
    "Oh, right...",
    "Right, okay...",
    "Sure, okay...",
    "Yeah, okay...",
    "Hmm, okay...",
    "Ah, okay...",
    "Hmm, interesting...",
    "Oh, interesting...",
    "Right, interesting...",
    "Yeah, interesting...",
    "Okay, interesting...",
    "Ah, interesting...",
    "Hmm, yeah, so...",
    "Okay, yeah, so...",
    "Right, yeah, so...",
    "Yeah, right, so...",
    "Hmm, okay, so...",

    # ── Pausing / re-centering ───────────────────────────────────────────────
    "Wait, so...",
    "Wait, right...",
    "Hmm, wait...",
    "Right, wait...",
    "Okay, wait...",
    "Yeah, wait...",
    "Wait a moment...",
    "Hold on...",
    "Hold on a second...",
    "Hold on, so...",
    "One moment...",
    "One second...",
    "Give me a moment...",
    "Just a moment...",

    # ── Open invitations to continue (content-free) ──────────────────────────
    "Go on.",
    "Go on...",
    "Go on, please.",
    "Please, go on.",
    "Continue.",
    "Continue...",
    "Please continue.",
    "Carry on.",
    "Carry on...",
    "Keep going.",
    "Keep going...",
    "Tell me more.",
    "Tell me more...",
    "Say more.",
    "Say more...",
    "Say more about that.",
    "Say more about that...",
    "Tell me more about that.",
    "Tell me more about that...",
    "Walk me through that.",
    "Walk me through that...",
    "Walk me through it.",
    "Walk me through it...",
    "Break that down.",
    "Break that down...",
    "Break it down.",
    "Break it down...",
    "Unpack that.",
    "Unpack that...",
    "Unpack that for me.",
    "Unpack that for me...",
    "Expand on that.",
    "Expand on that...",
    "Dive into that.",
    "Dive into that...",
    "Go deeper on that.",
    "Go deeper on that...",
    "Elaborate on that.",
    "Elaborate on that...",
    "I'm listening.",
    "I'm listening...",
    "Still listening.",
    "Still listening...",
    "I'm here.",
    "I'm here...",
    "I'm all ears.",
    "You have my attention.",
    "And then what?",
    "And then?",
    "Then what?",
    "Then?",
    "What next?",
    "What then?",
    "And?",
    "So?",
    "How so?",
    "In what sense?",
    "In what way?",
    "How do you mean?",
    "Specifically?",
    "Can you say more?",
    "Can you elaborate?",
    "Can you break that down?",

    # ── Neutral exploratory phrases ──────────────────────────────────────────
    "Let's explore that.",
    "Let's explore that...",
    "Let's dig into that.",
    "Let's dig into that...",
    "Let's unpack that.",
    "Let's unpack that...",
    "Let's work through it.",
    "Let's work through it...",
    "Let's think this through.",
    "Let's think this through...",
    "Let's reason through that.",
    "Let's reason through that...",
    "Let's talk through it.",
    "Let's talk through it...",
    "Let me hear more.",
    "Let me hear more...",
    "Let me dig into that.",
    "Let me dig into that...",
    "Let me explore that.",
    "Let me explore that...",
    "Let me unpack that.",
    "Let me unpack that...",
    "Let me walk through that.",
    "Let me walk through that...",
    "Okay, let's dig in.",
    "Okay, let's dig in...",
    "Right, let's dig in.",
    "Right, let's dig in...",
    "Good, let's dig in.",
    "Good, let's dig in...",
    "Okay, let's work through it.",
    "Okay, let's work through it...",
    "Right, let's work through it.",
    "Right, let's work through it...",
    "Okay, let's think through it.",
    "Right, let's think through it.",
    "Okay, let me think through it.",
    "Right, let me think through it.",
    "Let me think that through.",
    "Let me think that through...",
]
